### ISSUE TITLE
Why resnet downloaded from here cannot work in VM?

### ISSUE THREAD

**Issue by XinshaoWang** [tensorflow/tpu#133]
First I downloaded the tpu package. 
Then I transfer it to VM. 

The code in the serve can run well. 
But code of this package cannot run in the server. 

A lot of bugs, when I solved one. Another one came out. 

I know the code  in the Cloud machine is different from github. Why they are inconsistent?

**Comment by saeta** [comment]
Hi @XinshaoWang !

The Cloud machine's are created with a compatible set of TensorFlow and TPU models. Because we are hard at work on the software stack, we are making regular changes. In particular, we are often introducing new APIs into TensorFlow to make programming TPUs easier. We often upgrade the TPU models (this repository) to use the new APIs as a way of documenting the best practices. Taking the latest version of the models and trying to run them on an older version of TensorFlow (which doesn't have the new helpers / utilities / APIs) will crash. (Note: we have been working very hard to make sure that code working on a previous version of TensorFlow/TPUs continues to work! It's going the opposite direction that you'll definitely run into issues.)

Hope this helps!
-Brennan

**Comment by XinshaoWang** [comment]
Hi, thank you so much. 

I am using the version on VM as it works in the VM. 

Then I transfer the version on VM to my local machine. I would like to train the model on my local machine using GPU as well. 
However I cannot make it. Could you please help me about it?

What changes need I make to make the model run on my local GPU?
https://github.com/tensorflow/tpu/tree/master/models/official/resnet 
This guide is too simple and does not make sense to me.
