### ISSUE TITLE
potential problem in _get_image_data function

### ISSUE THREAD

**Issue by ultrons** [tensorflow/tpu#184]
Hi, 

In jpeg_to_tf_record.py source code, _get_image_data_function has a coder input which entails a tensorflow graph to perform potential transformation on the image.
But inside this function, coder input is not really used for anything meaningful.
Since the image_data which is returned from this function is not coming from the tensorflow graph.
Therefore any transformations inserted in this graph are not really helpful.

secondly the function synopsis says  the image_buffer is JPEG encoding of RGB image. but in fact it is just raw bytes from open.

I think the following line in the function:
return image_data, height, width
should be replaced with:
return image.tostring(), height, width

in this case image is output of tensorflow transformation graph.
Any changes there would reflect in the output of this function, which is perhaps a useful behavior.

**Comment by saeta** [comment]
Hi @ultrons !

Thanks for reaching out about these issues. As it turns out, I think the code is doing okay. Concretely, `_get_image_data` calls `image = coder.decode_jpeg(image_data)` [here](https://github.com/tensorflow/tpu/blob/a6d2e2411ac3519034844c3aa8a26426e86d9e8d/tools/datasets/jpeg_to_tf_record.py#L127). [`coder.decode_jpeg`](https://github.com/tensorflow/tpu/blob/a6d2e2411ac3519034844c3aa8a26426e86d9e8d/tools/datasets/jpeg_to_tf_record.py#L100) calls [`session.run`](https://github.com/tensorflow/tpu/blob/a6d2e2411ac3519034844c3aa8a26426e86d9e8d/tools/datasets/jpeg_to_tf_record.py#L101) and feeds in the jpeg as part of the feed dict. That `session.run` call requests the output of the [`decode_jpeg` TensorFlow op](https://github.com/tensorflow/tpu/blob/a6d2e2411ac3519034844c3aa8a26426e86d9e8d/tools/datasets/jpeg_to_tf_record.py#L98), thereby executing the graph. If you'd like to do more transformations (e.g. [random flip](https://www.tensorflow.org/versions/r1.0/api_docs/python/tf/image/random_flip_left_right)), you could switch the `ImageCoder` class to something like the following:

```python

class ImageCoder(object):
  """Helper class that provides TensorFlow image coding utilities."""

  def __init__(self):
    # Create a single Session to run all image coding calls.
    self._sess = tf.Session()

    # Initializes function that decodes RGB JPEG data.
    self._decode_jpeg_data = tf.placeholder(dtype=tf.string)
    self._decode_jpeg = tf.image.decode_jpeg(self._decode_jpeg_data, channels=3)
    self._image_output = tf.image.random_flip_left_right(self._decode_jpeg, seed=1)

  def decode_jpeg(self, image_data):
    # Retrieve the output of the random_flip_left_right node in the TensorFlow graph.
    image = self._sess.run(
        self._image_output, feed_dict={self._decode_jpeg_data: image_data})
    assert len(image.shape) == 3
    assert image.shape[2] == 3
    return image

  def __del__(self):
    self._sess.close()
```

That said, you're right that after we decode the image into its raw pixel values (`image`), we return from the function [`image_data`](https://github.com/tensorflow/tpu/blob/a6d2e2411ac3519034844c3aa8a26426e86d9e8d/tools/datasets/jpeg_to_tf_record.py#L135) instead. This is definitely confusing and probably warrants a comment. What's going on is that when constructing the `TFRecord` files, we can save storage and bandwidth costs by using the compressed images (e.g. the bytes read from the file, which correspond to a jpeg-encoded image) instead of the uncompressed images.

Hope this helps!
-Brennan

**Comment by ultrons** [comment]
Thanks a lot Brennan.
