### ISSUE TITLE
bfloat16_scope problem

### ISSUE THREAD

**Issue by TropComplique** [tensorflow/tpu#189]
Hi. 
It is impossible to complete this tutorial:
https://cloud.google.com/tpu/docs/tutorials/resnet
(or run this code: https://github.com/tensorflow/tpu/tree/master/models/official/resnet).

It is because TPUs are only available with tensorflow version 1.9 
(when creating an instance with `ctpu` tool).
But for `tf.contrib.tpu.bfloat16_scope` you need 1.10.

**Comment by TropComplique** [comment]
Thank you for your response.
When approximately it is going to be available?

**Comment by TropComplique** [comment]
I found a solution to my problem.

After switching to r1.9 branch, I see that I need to use:
```
from tensorflow.contrib.tpu.python.tpu import bfloat16
with bfloat16.bfloat16_scope():
    ...
```

**Comment by rajivpb** [comment]
Yes; it's important to keep the reference models in sync with the version of TensorFlow that is available for Cloud TPU, so checking out the r1.9 branch was the right thing to do. 

To clarify, are you saying that you needed to make a code-change to the model's imports?

**Comment by TropComplique** [comment]
Yes.

**Comment by aman2930** [comment]
I was checking with tpu r1.9 branch: https://github.com/tensorflow/tpu/blob/r1.9/models/official/resnet/resnet_main.py
The fix is already there since months.
So, believe that no code-change is required if that branch is checked out.

Closing this issue now. 
Feel free to open it if require any more clarification.
