### ISSUE TITLE
Ability to save EfficientNet models.

### ISSUE THREAD

**Issue by pbaylies** [tensorflow/tpu#378]
Currently it's not possible to save the EfficientNet Model, or to save or serialize a Keras model that includes it, i.e., with model.save() or with pickle, or with export_saved_model(), etc. Also, saving the weights with save_weights() doesn't save almost all of the weights, so that doesn't work either. Are you planning on supporting this in the future, or is there a recommended way to save an EfficientNet Model, or a model that uses it?

**Comment by saberkun** [comment]
Hi,
EfficientNet model uses TensorFlow Estimator framework rather than keras.
During training, you will see checkpoints in the model directory. After that, you can export savedmodel for serving. 
Note that, although we wrap EfficientNet with Keras model, due to some incomplete features on keras side, we move back to tf.layers api and it will not be compatible with keras save_weights. 
Sorry about that.
We really need to rewrite quite a lot of stuff to get true keras interface working.

**Comment by pbaylies** [comment]
Hi @saberkun thanks for explaining the implementation details; at least I wasn't missing something obvious...

**Comment by saberkun** [comment]
Yup. Just treat the model as plain TF 1.x Estimator framework. Thanks

**Comment by drscarlat** [comment]
You can find the EfficientNet as a python file at https://www.kaggle.com/ratthachat/efficientnet/output
It seems to bypass the issues pbaylies has raised, but I'm still checking it out
