### ISSUE TITLE
About feature_size=1536 of MixNet

### ISSUE THREAD

**Issue by becauseofAI** [tensorflow/tpu#469]
The feature_size is the final feature size of mixnet output layer. But, why the value is 1536？Can we change it to other values without affecting the performance of the network, such as 1024, 2048?

**Comment by mingxingtan** [comment]
You should be able to use other values (like 1280) with limited accuracy loss. Usually bigger feature_size give better accuracy, but the difference is usually small.

The value 1536 comes from 1280 * 1.2, because i designed a search space that have different feature size ratios (like 1.2x, 1.0x, 0.75x)  based on 1280 (MobileNetV2/MnasNet setting).
